STATUS_ATIVO = "ativo"
STATUS_INADIMPLENTE = "inadimplente"
STATUS_LIQUIDADO = "liquidado"

STATUS_VALIDOS = [STATUS_ATIVO, STATUS_INADIMPLENTE, STATUS_LIQUIDADO]

PRAZOS_MESES = [12, 24, 36, 48, 60, 72, 84, 96]

TAXA_MIN = 1.40   # % a.m.
TAXA_MAX = 2.40   # % a.m.

VALOR_MIN_CONTRATO = 1_000.0
VALOR_MAX_CONTRATO = 150_000.0

STATUS_COLORS = {
    STATUS_ATIVO: "#2ecc71",
    STATUS_INADIMPLENTE: "#e74c3c",
    STATUS_LIQUIDADO: "#95a5a6",
}
